"""phase6 organization integration credentials

Revision ID: 026598ba5867
Revises: 9d76e396bcf6
Create Date: 2026-08-16 13:01:57.926628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026598ba5867'
down_revision: Union[str, Sequence[str], None] = '9d76e396bcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'GOOGLE_CALENDAR', 'WHATSAPP', name='integration_provider'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'ERROR', 'UNCONFIGURED', name='integration_status'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('encryption_format_version', sa.Integer(), nullable=False),
    sa.Column('encryption_key_version', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_integrations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_integrations')),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_org_integration_org_provider')
    )
    op.create_index('ix_org_integration_org_provider', 'organization_integrations', ['organization_id', 'provider'], unique=False)
    op.create_index('ix_security_audit_events_organization_id', 'security_audit_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_audit_events_organization_id', table_name='security_audit_events')
    op.drop_index('ix_org_integration_org_provider', table_name='organization_integrations')
    op.drop_table('organization_integrations')
    # ### end Alembic commands ###
