"""phase3 shadow sync failure ledger

Revision ID: 973f082fdc6e
Revises: 106bb657103e
Create Date: 2026-08-16 00:41:44.920283

Adds one new table only — core/db/models/shadow_sync.py's
ShadowSyncFailure, the record of CRM relational shadow-write failures
(see services/relational_sync_service.py and
docs/V2_PHASE3_CRM_DUAL_WRITE.md). No existing table changes; the
relational CRM entity tables (patients, appointments, etc.) already
existed dormant since Phase 0 and needed no schema changes for Phase 3.
The legacy memory_store table is untouched, as in every prior phase.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973f082fdc6e'
down_revision: Union[str, Sequence[str], None] = '106bb657103e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_sync_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('error_category', sa.String(length=60), nullable=False),
    sa.Column('error_summary', sa.String(length=500), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_shadow_sync_failures_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shadow_sync_failures'))
    )
    op.create_index(op.f('ix_shadow_sync_failures_created_at'), 'shadow_sync_failures', ['created_at'], unique=False)
    op.create_index(op.f('ix_shadow_sync_failures_entity'), 'shadow_sync_failures', ['entity'], unique=False)
    op.create_index(op.f('ix_shadow_sync_failures_error_category'), 'shadow_sync_failures', ['error_category'], unique=False)
    op.create_index(op.f('ix_shadow_sync_failures_external_id'), 'shadow_sync_failures', ['external_id'], unique=False)
    op.create_index(op.f('ix_shadow_sync_failures_organization_id'), 'shadow_sync_failures', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shadow_sync_failures_resolved'), 'shadow_sync_failures', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_sync_failures_resolved'), table_name='shadow_sync_failures')
    op.drop_index(op.f('ix_shadow_sync_failures_organization_id'), table_name='shadow_sync_failures')
    op.drop_index(op.f('ix_shadow_sync_failures_external_id'), table_name='shadow_sync_failures')
    op.drop_index(op.f('ix_shadow_sync_failures_error_category'), table_name='shadow_sync_failures')
    op.drop_index(op.f('ix_shadow_sync_failures_entity'), table_name='shadow_sync_failures')
    op.drop_index(op.f('ix_shadow_sync_failures_created_at'), table_name='shadow_sync_failures')
    op.drop_table('shadow_sync_failures')
    # ### end Alembic commands ###
