"""phase4 read mismatch ledger

Revision ID: 9d76e396bcf6
Revises: 973f082fdc6e
Create Date: 2026-08-16 02:23:10.158777

Adds one new table only — core/db/models/shadow_sync.py's
ReadMismatch, the read-side counterpart to Phase 3's ShadowSyncFailure
(see services/crm_read_router.py and docs/V2_PHASE4_READ_CUTOVER.md).
No existing table changes; the legacy memory_store table is untouched,
as in every prior phase.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d76e396bcf6'
down_revision: Union[str, Sequence[str], None] = '973f082fdc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_mismatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('mismatch_category', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_read_mismatches_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_mismatches'))
    )
    op.create_index(op.f('ix_read_mismatches_created_at'), 'read_mismatches', ['created_at'], unique=False)
    op.create_index(op.f('ix_read_mismatches_entity'), 'read_mismatches', ['entity'], unique=False)
    op.create_index(op.f('ix_read_mismatches_external_id'), 'read_mismatches', ['external_id'], unique=False)
    op.create_index(op.f('ix_read_mismatches_mismatch_category'), 'read_mismatches', ['mismatch_category'], unique=False)
    op.create_index(op.f('ix_read_mismatches_organization_id'), 'read_mismatches', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_read_mismatches_organization_id'), table_name='read_mismatches')
    op.drop_index(op.f('ix_read_mismatches_mismatch_category'), table_name='read_mismatches')
    op.drop_index(op.f('ix_read_mismatches_external_id'), table_name='read_mismatches')
    op.drop_index(op.f('ix_read_mismatches_entity'), table_name='read_mismatches')
    op.drop_index(op.f('ix_read_mismatches_created_at'), table_name='read_mismatches')
    op.drop_table('read_mismatches')
    # ### end Alembic commands ###
