"""phase1 identity and authorization

Revision ID: af9ede758982
Revises: ea0d12961575
Create Date: 2026-08-15 23:45:49.357110

Autogenerate only catches the two structural changes here (new
identity_audit_events table, users.last_login_at). It does NOT detect
enum *member* changes on the existing user_status/membership_status/
membership_role columns (autogenerate never diffs Python enum members
against a live Postgres native ENUM type) — those are added by hand
below, guarded to postgresql only since SQLite stores these columns as
plain VARCHAR (see the CHECK-constraint-free DDL Phase 0 already
produces there) and needs no migration for a value rename/addition.

Enum changes made here, mirroring core/db/models/identity.py:
- user_status:       INACTIVE -> DISABLED (renamed), + INVITED (added)
- membership_status:  INACTIVE -> DISABLED (renamed)
- membership_role:    THERAPIST -> PRACTITIONER (renamed),
                       + ADMIN, FINANCE, MARKETING (added)
  OWNER, RECEPTIONIST, VIEWER are unchanged.

This is safe to run against a fresh/empty database (the only case this
migration has actually been exercised against — no real Postgres
deployment has ever run `alembic upgrade head`, see
docs/V2_COEXISTENCE.md). RENAME VALUE and ADD VALUE are both used in
autocommit blocks since PostgreSQL cannot run ALTER TYPE ... ADD VALUE
inside the same transaction that might reference the new value.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9ede758982'
down_revision: Union[str, Sequence[str], None] = 'ea0d12961575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    if is_postgres:
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE user_status RENAME VALUE 'INACTIVE' TO 'DISABLED'")
            op.execute("ALTER TYPE user_status ADD VALUE IF NOT EXISTS 'INVITED'")
            op.execute("ALTER TYPE membership_status RENAME VALUE 'INACTIVE' TO 'DISABLED'")
            op.execute("ALTER TYPE membership_role RENAME VALUE 'THERAPIST' TO 'PRACTITIONER'")
            op.execute("ALTER TYPE membership_role ADD VALUE IF NOT EXISTS 'ADMIN'")
            op.execute("ALTER TYPE membership_role ADD VALUE IF NOT EXISTS 'FINANCE'")
            op.execute("ALTER TYPE membership_role ADD VALUE IF NOT EXISTS 'MARKETING'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('USER_CREATED', 'USER_DISABLED', 'USER_ACTIVATED', 'ORGANIZATION_CREATED', 'ORGANIZATION_ACTIVATED', 'ORGANIZATION_DEACTIVATED', 'MEMBERSHIP_CREATED', 'MEMBERSHIP_DISABLED', 'MEMBERSHIP_ACTIVATED', 'ROLE_CHANGED', name='identity_event_type'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_identity_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_identity_audit_events_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_identity_audit_events_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_identity_audit_events_target_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_audit_events'))
    )
    op.create_index(op.f('ix_identity_audit_events_created_at'), 'identity_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_identity_audit_events_event_type'), 'identity_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_identity_audit_events_organization_id'), 'identity_audit_events', ['organization_id'], unique=False)
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Note: PostgreSQL has no ALTER TYPE ... DROP VALUE, so the ADDed enum
    values (INVITED, ADMIN, FINANCE, MARKETING) cannot be removed here —
    only the RENAMEs are reversed. This is a known, documented Postgres
    limitation, not an oversight; those extra values sitting unused in
    the enum type is harmless on a schema nothing live reads yet.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_index(op.f('ix_identity_audit_events_organization_id'), table_name='identity_audit_events')
    op.drop_index(op.f('ix_identity_audit_events_event_type'), table_name='identity_audit_events')
    op.drop_index(op.f('ix_identity_audit_events_created_at'), table_name='identity_audit_events')
    op.drop_table('identity_audit_events')
    # ### end Alembic commands ###

    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"
    if is_postgres:
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE membership_role RENAME VALUE 'PRACTITIONER' TO 'THERAPIST'")
            op.execute("ALTER TYPE membership_status RENAME VALUE 'DISABLED' TO 'INACTIVE'")
            op.execute("ALTER TYPE user_status RENAME VALUE 'DISABLED' TO 'INACTIVE'")
