"""phase0 initial schema

Revision ID: ea0d12961575
Revises: 
Create Date: 2026-08-15 23:14:25.651589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0d12961575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='organization_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.Enum('MEDIUM', 'HIGH', name='approval_risk_level'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('execution_external_id', sa.String(length=60), nullable=True),
    sa.Column('recommendation_id', sa.String(length=60), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_approvals_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_approvals_org_external_id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_approvals_org_id')
    )
    op.create_table('corporate_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'PROPOSAL_SENT', 'WON', 'LOST', 'ARCHIVED', name='corporate_client_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_corporate_clients_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_clients')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_corporate_clients_org_external_id')
    )
    op.create_table('jarvis_learning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('PREFERENCE', 'RECOMMENDATION', 'OUTCOME', 'EXECUTION', name='jarvis_learning_record_type'), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jarvis_learning_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jarvis_learning_records')),
    sa.UniqueConstraint('organization_id', 'record_type', 'fingerprint', name='uq_jarvis_learning_org_type_fingerprint')
    )
    op.create_index(op.f('ix_jarvis_learning_records_record_type'), 'jarvis_learning_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_jarvis_learning_records_recorded_at'), 'jarvis_learning_records', ['recorded_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('WEBSITE', 'PHONE', 'WALK_IN', 'REFERRAL', 'OTHER', name='lead_source'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'BOOKED', 'CONVERTED', 'LOST', 'ARCHIVED', name='lead_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_leads_org_external_id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'THERAPIST', 'RECEPTIONIST', 'VIEWER', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='membership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_organization')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('google_review_link', sa.String(length=500), nullable=True),
    sa.Column('monthly_revenue', sa.Float(), nullable=True),
    sa.Column('monthly_expenses', sa.Float(), nullable=True),
    sa.Column('target_monthly_revenue', sa.Float(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_settings')),
    sa.UniqueConstraint('organization_id', name='uq_organization_settings_organization_id')
    )
    op.create_table('package_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='package_template_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_package_templates_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_templates')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_package_templates_org_external_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RENEWAL_DUE', 'ARCHIVED', name='patient_status'), nullable=False),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sessions_remaining', sa.Integer(), nullable=False),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_patients_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_patients_org_external_id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_patients_org_id')
    )
    op.create_table('scheduler_alert_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('item_key', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scheduler_alert_ledger_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_alert_ledger')),
    sa.UniqueConstraint('organization_id', 'check_name', 'item_key', name='uq_scheduler_ledger_org_check_item')
    )
    op.create_index(op.f('ix_scheduler_alert_ledger_check_name'), 'scheduler_alert_ledger', ['check_name'], unique=False)
    op.create_table('scheduler_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('alerts_raised', sa.Integer(), nullable=False),
    sa.Column('approvals_queued', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scheduler_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_runs'))
    )
    op.create_index(op.f('ix_scheduler_runs_check_name'), 'scheduler_runs', ['check_name'], unique=False)
    op.create_index(op.f('ix_scheduler_runs_ran_at'), 'scheduler_runs', ['ran_at'], unique=False)
    op.create_index(op.f('ix_scheduler_runs_run_id'), 'scheduler_runs', ['run_id'], unique=False)
    op.create_table('security_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('entity', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_audit_events'))
    )
    op.create_index(op.f('ix_security_audit_events_recorded_at'), 'security_audit_events', ['recorded_at'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='service_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_services_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_services_org_name')
    )
    op.create_table('therapists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='therapist_status'), nullable=False),
    sa.Column('weekly_capacity', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_therapists_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapists')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_therapists_org_external_id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_therapists_org_id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'ARCHIVED', name='appointment_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'patient_id'], ['patients.organization_id', 'patients.id'], name='fk_appointments_patient_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'therapist_id'], ['therapists.organization_id', 'therapists.id'], name='fk_appointments_therapist_same_org', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_appointments_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_appointments_org_external_id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_therapist_id'), 'appointments', ['therapist_id'], unique=False)
    op.create_table('execution_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommendation_id', sa.String(length=60), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'SENT', 'SIMULATED', 'FAILED', name='execution_status'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'approval_id'], ['approvals.organization_id', 'approvals.id'], name='fk_execution_queue_approval_same_org', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_execution_queue_items_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_queue_items')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_execution_queue_org_external_id')
    )
    op.create_index(op.f('ix_execution_queue_items_approval_id'), 'execution_queue_items', ['approval_id'], unique=False)
    op.create_index(op.f('ix_execution_queue_items_fingerprint'), 'execution_queue_items', ['fingerprint'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('sessions_remaining', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'PAUSED', 'ARCHIVED', name='package_status'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'patient_id'], ['patients.organization_id', 'patients.id'], name='fk_packages_patient_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_packages_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_packages_org_external_id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_packages_org_id')
    )
    op.create_index(op.f('ix_packages_patient_id'), 'packages', ['patient_id'], unique=False)
    op.create_table('progress_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('progress_summary', sa.Text(), nullable=False),
    sa.Column('progress_status', sa.String(length=80), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'patient_id'], ['patients.organization_id', 'patients.id'], name='fk_progress_notes_patient_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'therapist_id'], ['therapists.organization_id', 'therapists.id'], name='fk_progress_notes_therapist_same_org', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_progress_notes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_notes')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_progress_notes_org_external_id')
    )
    op.create_index(op.f('ix_progress_notes_patient_id'), 'progress_notes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_progress_notes_therapist_id'), 'progress_notes', ['therapist_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'REFUNDED', 'ARCHIVED', name='payment_status'), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'package_id'], ['packages.organization_id', 'packages.id'], name='fk_payments_package_same_org', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'patient_id'], ['patients.organization_id', 'patients.id'], name='fk_payments_patient_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_payments_org_external_id')
    )
    op.create_index(op.f('ix_payments_package_id'), 'payments', ['package_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_package_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_progress_notes_therapist_id'), table_name='progress_notes')
    op.drop_index(op.f('ix_progress_notes_patient_id'), table_name='progress_notes')
    op.drop_table('progress_notes')
    op.drop_index(op.f('ix_packages_patient_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_execution_queue_items_fingerprint'), table_name='execution_queue_items')
    op.drop_index(op.f('ix_execution_queue_items_approval_id'), table_name='execution_queue_items')
    op.drop_table('execution_queue_items')
    op.drop_index(op.f('ix_appointments_therapist_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('therapists')
    op.drop_table('services')
    op.drop_index(op.f('ix_security_audit_events_recorded_at'), table_name='security_audit_events')
    op.drop_table('security_audit_events')
    op.drop_index(op.f('ix_scheduler_runs_run_id'), table_name='scheduler_runs')
    op.drop_index(op.f('ix_scheduler_runs_ran_at'), table_name='scheduler_runs')
    op.drop_index(op.f('ix_scheduler_runs_check_name'), table_name='scheduler_runs')
    op.drop_table('scheduler_runs')
    op.drop_index(op.f('ix_scheduler_alert_ledger_check_name'), table_name='scheduler_alert_ledger')
    op.drop_table('scheduler_alert_ledger')
    op.drop_table('patients')
    op.drop_table('package_templates')
    op.drop_table('organization_settings')
    op.drop_table('memberships')
    op.drop_table('leads')
    op.drop_index(op.f('ix_jarvis_learning_records_recorded_at'), table_name='jarvis_learning_records')
    op.drop_index(op.f('ix_jarvis_learning_records_record_type'), table_name='jarvis_learning_records')
    op.drop_table('jarvis_learning_records')
    op.drop_table('corporate_clients')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
